# Documentation in https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/dev/cnf/dependabot"
    update_schedule: "daily"
    target_branch: "integration"
    allowed_updates:
      - match:
          update_type: "security"

